### ISSUE TITLE
Metadata alignment

### ISSUE THREAD

**Issue by chantallengua** [simayguzel/Knowledge-Organization-Project#4]
Following the GUIDELINES, the next step is the "Metadata alignment"
![image](https://user-images.githubusercontent.com/43709607/55178810-68f70f00-5186-11e9-8293-5ba7048a2bae.png)
Last year they did an excellent job: you can find their tables/excels here:

From ABITLOD:
[Alignment ABITLOD.pdf](https://github.com/simayguzel/Knowledge-Organization-Project/files/3019398/Alignment.ABITLOD.pdf)

From WATERLOD:
The short version, on the website:
[Alignment WaterLOD_short version.pdf](https://github.com/simayguzel/Knowledge-Organization-Project/files/3019403/Alignment.WaterLOD_short.version.pdf)
And the full version:
[Alignment WaterLOD.pdf](https://github.com/simayguzel/Knowledge-Organization-Project/files/3019400/Alignment.WaterLOD.pdf)

From GROCK:
The short version:
[Alignment GROCK.pdf](https://github.com/simayguzel/Knowledge-Organization-Project/files/3019407/Alignment.GROCK.pdf)
And the full one:
[Mapping.xlsx](https://github.com/simayguzel/Knowledge-Organization-Project/files/3019404/Mapping.xlsx)

They use things that we haven't seen during the course, but I think they are important, e.g. LIDO, PICO, MMD, CM, MODS, CDWA.

**Comment by chantallengua** [comment]
From what I understood, these are the standards we need in the "Alignment" step.
Useful Tomasi's slides n.2 = [2_CH-standard-KO.pdf](https://github.com/simayguzel/Knowledge-Organization-Project/files/3019453/2_CH-standard-KO.pdf)


**LIBRARIES:** 
(bibliography suggested by Tomasi in page 8 of slide 2: https://www.ifla.org/node/8750/)
From page 10 we can read that in libraries we need:
- content standards: ISBD (for bibliographic entries), RDA
- structure standards: MARC21, UNIMARC
Also important, even if I don't know if they are content or structure standards:
- FRBR
- TEI for manuscripts

**ARCHIVES:**
(bibliography suggested by Tomasi in page 8 of slide 2: https://www.ica.org/en/public-resources/standards)
From page 19 we can read that in archives we need:
- content standards: ISAD, ISAAR
- structure standards: EAD, EAC-CPF
Also important, even if I don't know if it is a content or structure standard:
- F entry for photographs (<-- you can read this in the Guidelines for the project)

**MUSEUMS:**
(bibliography suggested by Tomasi in page 8 of slide 2:  http://icom.museum/professional-standards/standards-guidelines but the link doesn't go...)
From page 32 we can read that in museums we need:
- data content: CCO (for paintings)
- data structure: CDWA
- CIDOC-CRM

**FOR EVERYTHING**:
- Dublin Core
- FOAF

And there are also these ones mentioned in the previous comment:
LIDO, PICO, MMD, CM, MODS, CDWA, VRA.

**Comment by chantallengua** [comment]
I still don't really get the difference between all these acronyms, in particular between ONTOLOGIES (like SKOS, FRBR, etc) and the standards we need to use in this step. Are they the same?
What are the models and the ontologies? Which relationship is there between those two?
And the vocabularies? And the data sets?

Regarding the first question, e.g. we can write in an "Alignment" document, as last year was done, that 
<dc.creator> is equal to <ead.persname> (I don't think it's right, but anyway)
But I can't write anything with SKOS, like <skos.something>, or <skos.creator> etc.
WHYYY? Are we already working with ontologies or not?

**Comment by lisasiurina** [comment]
@Chantallengua **I still don't really get the difference between all these acronyms, in particular between ONTOLOGIES (like SKOS, FRBR, etc) and the standards we need to use in this step. Are they the same?**

All these standards names (acronyms) represent different standards. They are different in the way that all organizations and institutions use and accommodate those guidelines for the standards that meet better their needs to track product, object details. 
Ex., here is the explanation for the reason behind the chosen standard **What about Metadata and Standards?** in the description of an item.
https://valentinapasqual.github.io/AbitLOD/

**What are the models and the ontologies? Which relationship is there between those two?
And the vocabularies? And the data sets?**

Viki's link explaining Vocabularies is awesome :)

**<dc.creator> is equal to <ead.persname> (I don't think it's right, but anyway)
But I can't write anything with SKOS, like <skos.something>, or <skos.creator> etc.
WHYYY?** 

Sorry, but I didn't understand your question. Would you explain? Why can't we use? In the Alignment part, we will describe the chosen ontology for an item.

**Comment by chantallengua** [comment]
Hi girls, I started the Alignment part.
As you know, we "Define the alignment between the different used standard for the metadata related to people, place, date, concepts".
I started with DC, which is the best and most common (and as Tomasi said, her favorite).
You can find the different metadata terms (i.e. the labels like "dc.creator" for defining the creator of a painting/artifacts in general, or "dc.date" for defining the date of that artifacts ecc...) here:
https://en.wikipedia.org/wiki/Dublin_Core#Dublin_Core_Metadata_Element_Set
(precisely, here: 
![image](https://user-images.githubusercontent.com/43709607/55281703-ab604d80-5338-11e9-8908-ae43af6fa018.png)
and on their site:
http://www.dublincore.org/specifications/dublin-core/dcmi-terms/
or here: https://terms.tdwg.org/wiki/Dublin_Core_elements_(1.1)_namespace

This is the result. I admit I lost most of the time with the layout.
[people place date concept.pdf](https://github.com/simayguzel/Knowledge-Organization-Project/files/3026059/people.place.date.concept.pdf)
You can change it in this Excel:
[people place date concept.xlsx](https://github.com/simayguzel/Knowledge-Organization-Project/files/3026058/people.place.date.concept.xlsx)
[you will find a thing in yellow: that's because I wasn't sure about it]

As you can see, I followed GROCK project's alignment (see here: [Mapping.xlsx](https://github.com/simayguzel/Knowledge-Organization-Project/files/3026060/Mapping.xlsx))
), the best and most complete one, in my opinion. But I spot some errors, in their DC labels (for example, for the date of the creation they used dc:date, but dc:created must be used, instead).

I added only the DC labels, but we have to choose 7 more ontologies, and write them under the DC labels (where there are the "?" symbols). Why 7? 
First of all because it was perfect with the layout :) and then, because in GROCK they chose 7 in total (while we will choose 8) and I think that the more they are the better and complete the mapping is.
Which ontologies should we choose?
The answer is in my second comment in this issue.

I think ISBD is very important, maybe we can choose between it and another content standard for libraries, i.e. RDA. 

In GROCK and WATERLOD project they didn't mention FRBR. Only AbitLOD mentioned it, but I think in a bad way (using only 3 FRBR labels, 2 in "WHO" and 1 in "WHAT", without, thus, using it in "WHEN" and "WHEREW. See here: 
[Alignment ABITLOD.pdf](https://github.com/simayguzel/Knowledge-Organization-Project/files/3026067/Alignment.ABITLOD.pdf)). I suggest, then, not taking it into consideration.

Here http://xmlns.com/foaf/spec/#sec-standards there is detailed information about FOAF. I will read them more tomorrow, so don't bother searching information about FOAF because I will look for it.

We can suggest the next 7 ontologies here in the comments, providing explanations and links... What do you think? Tomorrow afternoon I will return on the project and hopefully by the end of the weekend we can finish the "general alignment" part.
Also because, then, we have to do the metadata standards for EACH of our items, and that will be... hard :)
Kisses

**Comment by simayguzel** [comment]
/Users/simayguzel/Desktop/tomasi project.excel.xlsx

**Comment by simayguzel** [comment]
[tomasi project.excel.xlsx](https://github.com/simayguzel/Knowledge-Organization-Project/files/3026514/tomasi.project.excel.xlsx)

**QUESTIONS REGARDING THE EXCEL FILE**

- is it okay if an item is described in another language?
- should we include tags in the concept part for example; in https://digital.staatsbibliothek-berlin.de/werkansicht?PPN=PPN644115580&PHYSID=PHYS_0001&DMDID=DMDLOG_0001&view=overview-info in ‘Schlagwörter(which means tags in german)’ part
?
- in which part are we supposed to put the 'publishing house'; shall we think them as 'publisher' and write them in the 'person' part?
- http://opac.lbs-braunschweig.gbv.de/DB=2/CMD?ACT=SRCHA&IKT=1016&SRT=YOP&TRM=url+diglib.hab.dedruckebibel-s-4f-257start.htm? about this i don't know where to put the Publication statement.
i am not sure about the ‘credits’ in Martin Luther hanging his ninety five thesis.

**Comment by chantallengua** [comment]
> [tomasi project.excel.xlsx](https://github.com/simayguzel/Knowledge-Organization-Project/files/3026514/tomasi.project.excel.xlsx)
> 
> **QUESTIONS REGARDING THE EXCEL FILE**
> 
> * is it okay if an item is described in another language?
**Yes of course**

> * should we include tags in the concept part for example; in https://digital.staatsbibliothek-berlin.de/werkansicht?PPN=PPN644115580&PHYSID=PHYS_0001&DMDID=DMDLOG_0001&view=overview-info in ‘Schlagwörter(which means tags in german)’ part  ?
**No, I think they are optional and depends on the will of that particular museum/archive, so we can skip them. For example none of the previous projects mentioned them.**

> * in which part are we supposed to put the 'publishing house'; shall we think them as 'publisher' and write them in the 'person' part?
**It depends on the standard you are using. For example, DC says:
![image](https://user-images.githubusercontent.com/43709607/55289457-50c20280-53c7-11e9-8cbd-1b00f98b6354.png)
Thus I would put it in "PEOPLE". I think that it is quite the same for every standard, because "WHAT" regards specifically the item, its format, its subject/content etc. A publishing house is still made by real humans :)**

> * http://opac.lbs-braunschweig.gbv.de/DB=2/CMD?ACT=SRCHA&IKT=1016&SRT=YOP&TRM=url+diglib.hab.dedruckebibel-s-4f-257start.htm? about this i don't know where to put the Publication statement.
**I didn't understand the question... what do you mean with Publication statement?**

>   i am not sure about the ‘credits’ in Martin Luther hanging his ninety five thesis.
**The credits belong to the museum, generally. In this example, I can't really understand from their site. Maybe there is something in the annotations: "Becker seel sanbtl. Erben mir Georg Heinrich Vengen als Beystandt der 3 abwesenden Söhne u. Töchter bey der Erbtheilung dieses new Testament; Wappen-Exlibris: Elisabetha Sophia Maria Verwittwete Herzoginn Zu Br. U. Lun." They speak about three daughters and heirs, but from google translate it is impossible to understand the abbreviations. Maybe we can ask Severin**

**Comment by chantallengua** [comment]
UPDATE: I ADDED ISBD ON THE ALIGNMENT.

you can find it here: 
[people place date concept.pdf](https://github.com/simayguzel/Knowledge-Organization-Project/files/3027061/people.place.date.concept.pdf) and modify it here: 
[people place date concept.xlsx](https://github.com/simayguzel/Knowledge-Organization-Project/files/3027062/people.place.date.concept.xlsx)

I followed these links, as bibliography:
http://metadataregistry.org/schemaprop/list/page/1/schema_id/25.html
https://www.ifla.org/files/assets/cataloguing/isbd/OtherDocumentation/guidelines-use-isbdld_082016.0.pdf
https://www.ifla.org/files/assets/cataloguing/isbd/OtherDocumentation/isbd-rda-reicat_table.pdf
https://www.ifla.org/files/assets/cataloguing/isbd/isbd-cons_20110321.pdf

I wrote in the form of RDFS, because the mapping / alignment is made in RDFS, as it is written here:
![image](https://user-images.githubusercontent.com/43709607/55293950-846b4f80-53fc-11e9-9501-354109f8e181.png)
![image](https://user-images.githubusercontent.com/43709607/55293951-89300380-53fc-11e9-81f6-ab3ab4654033.png)
(from https://www.ifla.org/files/assets/cataloguing/isbd/OtherDocumentation/guidelines-use-isbdld_082016.0.pdf)

**Comment by simayguzel** [comment]
https://archive.ifla.org/VII/s13/guide/metaguide03.pdf
